# Code generated from OpenAPI specs by Databricks SDK Generator. DO NOT EDIT.


#' 
#' @section Operations:
#' \tabular{ll}{
#'  \link[=model_versions_create]{create} \tab Create a model version.\cr
#'  \link[=model_versions_delete]{delete} \tab Delete a model version.\cr
#'  \link[=model_versions_delete_tag]{delete_tag} \tab Delete a model version tag.\cr
#'  \link[=model_versions_get]{get} \tab Get a model version.\cr
#'  \link[=model_versions_get_download_uri]{get_download_uri} \tab Get a model version URI.\cr
#'  \link[=model_versions_search]{search} \tab Searches model versions.\cr
#'  \link[=model_versions_set_tag]{set_tag} \tab Set a version tag.\cr
#'  \link[=model_versions_transition_stage]{transition_stage} \tab Transition a stage.\cr
#'  \link[=model_versions_update]{update} \tab Update model version.\cr
#' }
#'
#' @rdname model_versions
#' @export
model_versions <- list()

#' Create a model version.
#' 
#' Creates a model version.
#'
#' @param description Optional description for model version.
#' @param name [required] Register model under this name.
#' @param run_id MLflow run ID for correlation, if `source` was generated by an experiment run in MLflow tracking server.
#' @param run_link MLflow run link - this is the exact link of the run that generated this model version, potentially hosted at another instance of MLflow.
#' @param source [required] URI indicating the location of the model artifacts.
#' @param tags Additional metadata for model version.
#'
#' @keywords internal
#'
#' @rdname model_versions_create
#'
#' @aliases model_versions_create
model_versions_create <- function(name, source, description = NULL, run_id = NULL,
  run_link = NULL, tags = NULL, ...) {
  body <- list(description = description, name = name, run_id = run_id, run_link = run_link,
    source = source, tags = tags, ...)

  .api$do("POST", "/api/2.0/mlflow/model-versions/create", body = body)
}
model_versions$create <- model_versions_create

#' Delete a model version.
#' 
#' Deletes a model version.
#'
#' @param name [required] Name of the registered model.
#' @param version [required] Model version number.
#'
#' @keywords internal
#'
#' @rdname model_versions_delete
#'
#' @aliases model_versions_delete
model_versions_delete <- function(name, version, ...) {
  query <- list(name = name, version = version, ...)

  .api$do("DELETE", "/api/2.0/mlflow/model-versions/delete", query = query)
}
model_versions$delete <- model_versions_delete

#' Delete a model version tag.
#' 
#' Deletes a model version tag.
#'
#' @param key [required] Name of the tag.
#' @param name [required] Name of the registered model that the tag was logged under.
#' @param version [required] Model version number that the tag was logged under.
#'
#' @keywords internal
#'
#' @rdname model_versions_delete_tag
#'
#' @aliases model_versions_delete_tag
model_versions_delete_tag <- function(name, version, key, ...) {
  query <- list(key = key, name = name, version = version, ...)

  .api$do("DELETE", "/api/2.0/mlflow/model-versions/delete-tag", query = query)
}
model_versions$delete_tag <- model_versions_delete_tag

#' Get a model version.
#' 
#' Get a model version.
#'
#' @param name [required] Name of the registered model.
#' @param version [required] Model version number.
#'
#' @keywords internal
#'
#' @rdname model_versions_get
#'
#' @aliases model_versions_get
model_versions_get <- function(name, version, ...) {
  query <- list(name = name, version = version, ...)

  .api$do("GET", "/api/2.0/mlflow/model-versions/get", query = query)
}
model_versions$get <- model_versions_get

#' Get a model version URI.
#' 
#' Gets a URI to download the model version.
#'
#' @param name [required] Name of the registered model.
#' @param version [required] Model version number.
#'
#' @keywords internal
#'
#' @rdname model_versions_get_download_uri
#'
#' @aliases model_versions_get_download_uri
model_versions_get_download_uri <- function(name, version, ...) {
  query <- list(name = name, version = version, ...)

  .api$do("GET", "/api/2.0/mlflow/model-versions/get-download-uri", query = query)
}
model_versions$get_download_uri <- model_versions_get_download_uri

#' Searches model versions.
#' 
#' Searches for specific model versions based on the supplied __filter__.
#'
#' @param filter String filter condition, like 'name='my-model-name''.
#' @param max_results Maximum number of models desired.
#' @param order_by List of columns to be ordered by including model name, version, stage with an optional 'DESC' or 'ASC' annotation, where 'ASC' is the default.
#' @param page_token Pagination token to go to next page based on previous search query.
#' 
#' @return `data.frame` with all of the response pages.
#'
#' @keywords internal
#'
#' @rdname model_versions_search
#'
#' @aliases model_versions_search
model_versions_search <- function(filter = NULL, max_results = NULL, order_by = NULL,
  page_token = NULL, ...) {
  query <- list(filter = filter, max_results = max_results, order_by = order_by,
    page_token = page_token, ...)



  results <- data.frame()
  while (TRUE) {
    json <- .api$do("GET", "/api/2.0/mlflow/model-versions/search", query = query)
    if (is.null(nrow(json$model_versions))) {
      break
    }
    # append this page of results to one results data.frame
    results <- dplyr::bind_rows(results, json$model_versions)
    if (is.null(json$next_page_token)) {
      break
    }
    query$page_token <- json$next_page_token
  }
  return(results)

}
model_versions$search <- model_versions_search

#' Set a version tag.
#' 
#' Sets a model version tag.
#'
#' @param key [required] Name of the tag.
#' @param name [required] Unique name of the model.
#' @param value [required] String value of the tag being logged.
#' @param version [required] Model version number.
#'
#' @keywords internal
#'
#' @rdname model_versions_set_tag
#'
#' @aliases model_versions_set_tag
model_versions_set_tag <- function(name, version, key, value, ...) {
  body <- list(key = key, name = name, value = value, version = version, ...)

  .api$do("POST", "/api/2.0/mlflow/model-versions/set-tag", body = body)
}
model_versions$set_tag <- model_versions_set_tag

#' Transition a stage.
#' 
#' Transition to the next model stage.
#'
#' @param archive_existing_versions [required] When transitioning a model version to a particular stage, this flag dictates whether all existing model versions in that stage should be atomically moved to the 'archived' stage.
#' @param name [required] Name of the registered model.
#' @param stage [required] Transition `model_version` to new stage.
#' @param version [required] Model version number.
#'
#' @keywords internal
#'
#' @rdname model_versions_transition_stage
#'
#' @aliases model_versions_transition_stage
model_versions_transition_stage <- function(name, version, stage, archive_existing_versions,
  ...) {
  body <- list(archive_existing_versions = archive_existing_versions, name = name,
    stage = stage, version = version, ...)

  .api$do("POST", "/api/2.0/mlflow/model-versions/transition-stage", body = body)
}
model_versions$transition_stage <- model_versions_transition_stage

#' Update model version.
#' 
#' Updates the model version.
#'
#' @param description If provided, updates the description for this `registered_model`.
#' @param name [required] Name of the registered model.
#' @param version [required] Model version number.
#'
#' @keywords internal
#'
#' @rdname model_versions_update
#'
#' @aliases model_versions_update
model_versions_update <- function(name, version, description = NULL, ...) {
  body <- list(description = description, name = name, version = version, ...)

  .api$do("PATCH", "/api/2.0/mlflow/model-versions/update", body = body)
}
model_versions$update <- model_versions_update













