# Code generated from OpenAPI specs by Databricks SDK Generator. DO NOT EDIT.

#' @importFrom stats runif
NULL

#' Approve transition request.
#' 
#' Approves a model version stage transition request.
#' @param client Required. Instance of DatabricksClient()


#'
#'
#' @param archive_existing_versions Required. Specifies whether to archive all current model versions in the target stage.
#' @param comment User-provided comment on the action.
#' @param name Required. Name of the model.
#' @param stage Required. Target stage of the transition.
#' @param version Required. Version of the model.
#'
#' @rdname modelRegistryApproveTransitionRequest
#' @export
modelRegistryApproveTransitionRequest <- function(client, name, version, stage, archive_existing_versions,
  comment = NULL) {
  body <- list(archive_existing_versions = archive_existing_versions, comment = comment,
    name = name, stage = stage, version = version)
  client$do("POST", "/api/2.0/mlflow/transition-requests/approve", body = body)
}

#' Post a comment.
#' 
#' Posts a comment on a model version. A comment can be submitted either by a
#' user or programmatically to display relevant information about the model. For
#' example, test results or deployment errors.
#' @param client Required. Instance of DatabricksClient()


#'
#'
#' @param comment Required. User-provided comment on the action.
#' @param name Required. Name of the model.
#' @param version Required. Version of the model.
#'
#' @rdname modelRegistryCreateComment
#' @export
modelRegistryCreateComment <- function(client, name, version, comment) {
  body <- list(comment = comment, name = name, version = version)
  client$do("POST", "/api/2.0/mlflow/comments/create", body = body)
}

#' Create a model.
#' 
#' Creates a new registered model with the name specified in the request body.
#' 
#' Throws `RESOURCE_ALREADY_EXISTS` if a registered model with the given name
#' exists.
#' @param client Required. Instance of DatabricksClient()


#'
#'
#' @param description Optional description for registered model.
#' @param name Required. Register models under this name.
#' @param tags Additional metadata for registered model.
#'
#' @rdname modelRegistryCreateModel
#' @export
modelRegistryCreateModel <- function(client, name, description = NULL, tags = NULL) {
  body <- list(description = description, name = name, tags = tags)
  client$do("POST", "/api/2.0/mlflow/registered-models/create", body = body)
}

#' Create a model version.
#' 
#' Creates a model version.
#' @param client Required. Instance of DatabricksClient()


#'
#'
#' @param description Optional description for model version.
#' @param name Required. Register model under this name.
#' @param run_id MLflow run ID for correlation, if `source` was generated by an experiment run in MLflow tracking server.
#' @param run_link MLflow run link - this is the exact link of the run that generated this model version, potentially hosted at another instance of MLflow.
#' @param source Required. URI indicating the location of the model artifacts.
#' @param tags Additional metadata for model version.
#'
#' @rdname modelRegistryCreateModelVersion
#' @export
modelRegistryCreateModelVersion <- function(client, name, source, description = NULL,
  run_id = NULL, run_link = NULL, tags = NULL) {
  body <- list(description = description, name = name, run_id = run_id, run_link = run_link,
    source = source, tags = tags)
  client$do("POST", "/api/2.0/mlflow/model-versions/create", body = body)
}

#' Make a transition request.
#' 
#' Creates a model version stage transition request.
#' @param client Required. Instance of DatabricksClient()


#'
#'
#' @param comment User-provided comment on the action.
#' @param name Required. Name of the model.
#' @param stage Required. Target stage of the transition.
#' @param version Required. Version of the model.
#'
#' @rdname modelRegistryCreateTransitionRequest
#' @export
modelRegistryCreateTransitionRequest <- function(client, name, version, stage, comment = NULL) {
  body <- list(comment = comment, name = name, stage = stage, version = version)
  client$do("POST", "/api/2.0/mlflow/transition-requests/create", body = body)
}

#' Create a webhook.
#' 
#' **NOTE**: This endpoint is in Public Preview.
#' 
#' Creates a registry webhook.
#' @param client Required. Instance of DatabricksClient()


#'
#'
#' @param description User-specified description for the webhook.
#' @param events Required. Events that can trigger a registry webhook: * `MODEL_VERSION_CREATED`: A new model version was created for the associated model.
#' @param http_url_spec This field has no description yet.
#' @param job_spec This field has no description yet.
#' @param model_name Name of the model whose events would trigger this webhook.
#' @param status Enable or disable triggering the webhook, or put the webhook into test mode.
#'
#' @rdname modelRegistryCreateWebhook
#' @export
modelRegistryCreateWebhook <- function(client, events, description = NULL, http_url_spec = NULL,
  job_spec = NULL, model_name = NULL, status = NULL) {
  body <- list(description = description, events = events, http_url_spec = http_url_spec,
    job_spec = job_spec, model_name = model_name, status = status)
  client$do("POST", "/api/2.0/mlflow/registry-webhooks/create", body = body)
}

#' Delete a comment.
#' 
#' Deletes a comment on a model version.
#' @param client Required. Instance of DatabricksClient()


#'
#'
#' @param id Required. This field has no description yet.
#'
#' @rdname modelRegistryDeleteComment
#' @export
modelRegistryDeleteComment <- function(client, id) {
  query <- list(id = id)
  client$do("DELETE", "/api/2.0/mlflow/comments/delete", query = query)
}

#' Delete a model.
#' 
#' Deletes a registered model.
#' @param client Required. Instance of DatabricksClient()


#'
#'
#' @param name Required. Registered model unique name identifier.
#'
#' @rdname modelRegistryDeleteModel
#' @export
modelRegistryDeleteModel <- function(client, name) {
  query <- list(name = name)
  client$do("DELETE", "/api/2.0/mlflow/registered-models/delete", query = query)
}

#' Delete a model tag.
#' 
#' Deletes the tag for a registered model.
#' @param client Required. Instance of DatabricksClient()


#'
#'
#' @param key Required. Name of the tag.
#' @param name Required. Name of the registered model that the tag was logged under.
#'
#' @rdname modelRegistryDeleteModelTag
#' @export
modelRegistryDeleteModelTag <- function(client, name, key) {
  query <- list(key = key, name = name)
  client$do("DELETE", "/api/2.0/mlflow/registered-models/delete-tag", query = query)
}

#' Delete a model version.
#' 
#' Deletes a model version.
#' @param client Required. Instance of DatabricksClient()


#'
#'
#' @param name Required. Name of the registered model.
#' @param version Required. Model version number.
#'
#' @rdname modelRegistryDeleteModelVersion
#' @export
modelRegistryDeleteModelVersion <- function(client, name, version) {
  query <- list(name = name, version = version)
  client$do("DELETE", "/api/2.0/mlflow/model-versions/delete", query = query)
}

#' Delete a model version tag.
#' 
#' Deletes a model version tag.
#' @param client Required. Instance of DatabricksClient()


#'
#'
#' @param key Required. Name of the tag.
#' @param name Required. Name of the registered model that the tag was logged under.
#' @param version Required. Model version number that the tag was logged under.
#'
#' @rdname modelRegistryDeleteModelVersionTag
#' @export
modelRegistryDeleteModelVersionTag <- function(client, name, version, key) {
  query <- list(key = key, name = name, version = version)
  client$do("DELETE", "/api/2.0/mlflow/model-versions/delete-tag", query = query)
}

#' Delete a transition request.
#' 
#' Cancels a model version stage transition request.
#' @param client Required. Instance of DatabricksClient()


#'
#'
#' @param comment User-provided comment on the action.
#' @param creator Required. Username of the user who created this request.
#' @param name Required. Name of the model.
#' @param stage Required. Target stage of the transition request.
#' @param version Required. Version of the model.
#'
#' @rdname modelRegistryDeleteTransitionRequest
#' @export
modelRegistryDeleteTransitionRequest <- function(client, name, version, stage, creator,
  comment = NULL) {
  query <- list(comment = comment, creator = creator, name = name, stage = stage,
    version = version)
  client$do("DELETE", "/api/2.0/mlflow/transition-requests/delete", query = query)
}

#' Delete a webhook.
#' 
#' **NOTE:** This endpoint is in Public Preview.
#' 
#' Deletes a registry webhook.
#' @param client Required. Instance of DatabricksClient()


#'
#' @param id Webhook ID required to delete a registry webhook.
#'
#' @rdname modelRegistryDeleteWebhook
#' @export
modelRegistryDeleteWebhook <- function(client, id = NULL) {
  query <- list(id = id)
  client$do("DELETE", "/api/2.0/mlflow/registry-webhooks/delete", query = query)
}

#' Get the latest version.
#' 
#' Gets the latest version of a registered model.
#' @param client Required. Instance of DatabricksClient()


#'
#'
#' @param name Required. Registered model unique name identifier.
#' @param stages List of stages.
#'
#' @return `data.frame` with all of the response pages.
#'
#' @rdname modelRegistryGetLatestVersions
#' @export
modelRegistryGetLatestVersions <- function(client, name, stages = NULL) {
  body <- list(name = name, stages = stages)

  json <- client$do("POST", "/api/2.0/mlflow/registered-models/get-latest-versions",
    body = body)
  return(json$model_versions)

}

#' Get model.
#' 
#' Get the details of a model. This is a Databricks workspace version of the
#' [MLflow endpoint] that also returns the model's Databricks workspace ID and
#' the permission level of the requesting user on the model.
#' 
#' [MLflow endpoint]: https://www.mlflow.org/docs/latest/rest-api.html#get-registeredmodel
#' @param client Required. Instance of DatabricksClient()


#'
#'
#' @param name Required. Registered model unique name identifier.
#'
#' @rdname modelRegistryGetModel
#' @export
modelRegistryGetModel <- function(client, name) {
  query <- list(name = name)
  client$do("GET", "/api/2.0/mlflow/databricks/registered-models/get", query = query)
}

#' Get a model version.
#' 
#' Get a model version.
#' @param client Required. Instance of DatabricksClient()


#'
#'
#' @param name Required. Name of the registered model.
#' @param version Required. Model version number.
#'
#' @rdname modelRegistryGetModelVersion
#' @export
modelRegistryGetModelVersion <- function(client, name, version) {
  query <- list(name = name, version = version)
  client$do("GET", "/api/2.0/mlflow/model-versions/get", query = query)
}

#' Get a model version URI.
#' 
#' Gets a URI to download the model version.
#' @param client Required. Instance of DatabricksClient()


#'
#'
#' @param name Required. Name of the registered model.
#' @param version Required. Model version number.
#'
#' @rdname modelRegistryGetModelVersionDownloadUri
#' @export
modelRegistryGetModelVersionDownloadUri <- function(client, name, version) {
  query <- list(name = name, version = version)
  client$do("GET", "/api/2.0/mlflow/model-versions/get-download-uri", query = query)
}

#' Get registered model permission levels.
#' 
#' Gets the permission levels that a user can have on an object.
#' @param client Required. Instance of DatabricksClient()


#'
#'
#' @param registered_model_id Required. The registered model for which to get or manage permissions.
#'
#' @rdname modelRegistryGetPermissionLevels
#' @export
modelRegistryGetPermissionLevels <- function(client, registered_model_id) {

  client$do("GET", paste("/api/2.0/permissions/registered-models/", registered_model_id,
    "/permissionLevels", , sep = ""))
}

#' Get registered model permissions.
#' 
#' Gets the permissions of a registered model. Registered models can inherit
#' permissions from their root object.
#' @param client Required. Instance of DatabricksClient()


#'
#'
#' @param registered_model_id Required. The registered model for which to get or manage permissions.
#'
#' @rdname modelRegistryGetPermissions
#' @export
modelRegistryGetPermissions <- function(client, registered_model_id) {

  client$do("GET", paste("/api/2.0/permissions/registered-models/", registered_model_id,
    sep = ""))
}

#' List models.
#' 
#' Lists all available registered models, up to the limit specified in
#' __max_results__.
#' @param client Required. Instance of DatabricksClient()


#'
#' @param max_results Maximum number of registered models desired.
#' @param page_token Pagination token to go to the next page based on a previous query.
#'
#' @return `data.frame` with all of the response pages.
#'
#' @rdname modelRegistryListModels
#' @export
modelRegistryListModels <- function(client, max_results = NULL, page_token = NULL) {
  query <- list(max_results = max_results, page_token = page_token)

  results <- data.frame()
  while (TRUE) {
    json <- client$do("GET", "/api/2.0/mlflow/registered-models/list", query = query)
    if (is.null(nrow(json$registered_models))) {
      break
    }
    # append this page of results to one results data.frame
    results <- dplyr::bind_rows(results, json$registered_models)
    if (is.null(json$next_page_token)) {
      break
    }
    query$page_token <- json$next_page_token
  }
  return(results)

}

#' List transition requests.
#' 
#' Gets a list of all open stage transition requests for the model version.
#' @param client Required. Instance of DatabricksClient()


#'
#'
#' @param name Required. Name of the model.
#' @param version Required. Version of the model.
#'
#' @return `data.frame` with all of the response pages.
#'
#' @rdname modelRegistryListTransitionRequests
#' @export
modelRegistryListTransitionRequests <- function(client, name, version) {
  query <- list(name = name, version = version)

  json <- client$do("GET", "/api/2.0/mlflow/transition-requests/list", query = query)
  return(json$requests)

}

#' List registry webhooks.
#' 
#' **NOTE:** This endpoint is in Public Preview.
#' 
#' Lists all registry webhooks.
#' @param client Required. Instance of DatabricksClient()


#'
#' @param events If `events` is specified, any webhook with one or more of the specified trigger events is included in the output.
#' @param model_name If not specified, all webhooks associated with the specified events are listed, regardless of their associated model.
#' @param page_token Token indicating the page of artifact results to fetch.
#'
#' @return `data.frame` with all of the response pages.
#'
#' @rdname modelRegistryListWebhooks
#' @export
modelRegistryListWebhooks <- function(client, events = NULL, model_name = NULL, page_token = NULL) {
  query <- list(events = events, model_name = model_name, page_token = page_token)

  results <- data.frame()
  while (TRUE) {
    json <- client$do("GET", "/api/2.0/mlflow/registry-webhooks/list", query = query)
    if (is.null(nrow(json$webhooks))) {
      break
    }
    # append this page of results to one results data.frame
    results <- dplyr::bind_rows(results, json$webhooks)
    if (is.null(json$next_page_token)) {
      break
    }
    query$page_token <- json$next_page_token
  }
  return(results)

}

#' Reject a transition request.
#' 
#' Rejects a model version stage transition request.
#' @param client Required. Instance of DatabricksClient()


#'
#'
#' @param comment User-provided comment on the action.
#' @param name Required. Name of the model.
#' @param stage Required. Target stage of the transition.
#' @param version Required. Version of the model.
#'
#' @rdname modelRegistryRejectTransitionRequest
#' @export
modelRegistryRejectTransitionRequest <- function(client, name, version, stage, comment = NULL) {
  body <- list(comment = comment, name = name, stage = stage, version = version)
  client$do("POST", "/api/2.0/mlflow/transition-requests/reject", body = body)
}

#' Rename a model.
#' 
#' Renames a registered model.
#' @param client Required. Instance of DatabricksClient()


#'
#'
#' @param name Required. Registered model unique name identifier.
#' @param new_name If provided, updates the name for this `registered_model`.
#'
#' @rdname modelRegistryRenameModel
#' @export
modelRegistryRenameModel <- function(client, name, new_name = NULL) {
  body <- list(name = name, new_name = new_name)
  client$do("POST", "/api/2.0/mlflow/registered-models/rename", body = body)
}

#' Searches model versions.
#' 
#' Searches for specific model versions based on the supplied __filter__.
#' @param client Required. Instance of DatabricksClient()


#'
#' @param filter String filter condition, like 'name='my-model-name''.
#' @param max_results Maximum number of models desired.
#' @param order_by List of columns to be ordered by including model name, version, stage with an optional 'DESC' or 'ASC' annotation, where 'ASC' is the default.
#' @param page_token Pagination token to go to next page based on previous search query.
#'
#' @return `data.frame` with all of the response pages.
#'
#' @rdname modelRegistrySearchModelVersions
#' @export
modelRegistrySearchModelVersions <- function(client, filter = NULL, max_results = NULL,
  order_by = NULL, page_token = NULL) {
  query <- list(filter = filter, max_results = max_results, order_by = order_by,
    page_token = page_token)

  results <- data.frame()
  while (TRUE) {
    json <- client$do("GET", "/api/2.0/mlflow/model-versions/search", query = query)
    if (is.null(nrow(json$model_versions))) {
      break
    }
    # append this page of results to one results data.frame
    results <- dplyr::bind_rows(results, json$model_versions)
    if (is.null(json$next_page_token)) {
      break
    }
    query$page_token <- json$next_page_token
  }
  return(results)

}

#' Search models.
#' 
#' Search for registered models based on the specified __filter__.
#' @param client Required. Instance of DatabricksClient()


#'
#' @param filter String filter condition, like 'name LIKE 'my-model-name''.
#' @param max_results Maximum number of models desired.
#' @param order_by List of columns for ordering search results, which can include model name and last updated timestamp with an optional 'DESC' or 'ASC' annotation, where 'ASC' is the default.
#' @param page_token Pagination token to go to the next page based on a previous search query.
#'
#' @return `data.frame` with all of the response pages.
#'
#' @rdname modelRegistrySearchModels
#' @export
modelRegistrySearchModels <- function(client, filter = NULL, max_results = NULL,
  order_by = NULL, page_token = NULL) {
  query <- list(filter = filter, max_results = max_results, order_by = order_by,
    page_token = page_token)

  results <- data.frame()
  while (TRUE) {
    json <- client$do("GET", "/api/2.0/mlflow/registered-models/search", query = query)
    if (is.null(nrow(json$registered_models))) {
      break
    }
    # append this page of results to one results data.frame
    results <- dplyr::bind_rows(results, json$registered_models)
    if (is.null(json$next_page_token)) {
      break
    }
    query$page_token <- json$next_page_token
  }
  return(results)

}

#' Set a tag.
#' 
#' Sets a tag on a registered model.
#' @param client Required. Instance of DatabricksClient()


#'
#'
#' @param key Required. Name of the tag.
#' @param name Required. Unique name of the model.
#' @param value Required. String value of the tag being logged.
#'
#' @rdname modelRegistrySetModelTag
#' @export
modelRegistrySetModelTag <- function(client, name, key, value) {
  body <- list(key = key, name = name, value = value)
  client$do("POST", "/api/2.0/mlflow/registered-models/set-tag", body = body)
}

#' Set a version tag.
#' 
#' Sets a model version tag.
#' @param client Required. Instance of DatabricksClient()


#'
#'
#' @param key Required. Name of the tag.
#' @param name Required. Unique name of the model.
#' @param value Required. String value of the tag being logged.
#' @param version Required. Model version number.
#'
#' @rdname modelRegistrySetModelVersionTag
#' @export
modelRegistrySetModelVersionTag <- function(client, name, version, key, value) {
  body <- list(key = key, name = name, value = value, version = version)
  client$do("POST", "/api/2.0/mlflow/model-versions/set-tag", body = body)
}

#' Set registered model permissions.
#' 
#' Sets permissions on a registered model. Registered models can inherit
#' permissions from their root object.
#' @param client Required. Instance of DatabricksClient()


#'
#'
#' @param access_control_list This field has no description yet.
#' @param registered_model_id Required. The registered model for which to get or manage permissions.
#'
#' @rdname modelRegistrySetPermissions
#' @export
modelRegistrySetPermissions <- function(client, registered_model_id, access_control_list = NULL) {
  body <- list(access_control_list = access_control_list)
  client$do("PUT", paste("/api/2.0/permissions/registered-models/", registered_model_id,
    sep = ""), body = body)
}

#' Test a webhook.
#' 
#' **NOTE:** This endpoint is in Public Preview.
#' 
#' Tests a registry webhook.
#' @param client Required. Instance of DatabricksClient()


#'
#'
#' @param event If `event` is specified, the test trigger uses the specified event.
#' @param id Required. Webhook ID.
#'
#' @rdname modelRegistryTestRegistryWebhook
#' @export
modelRegistryTestRegistryWebhook <- function(client, id, event = NULL) {
  body <- list(event = event, id = id)
  client$do("POST", "/api/2.0/mlflow/registry-webhooks/test", body = body)
}

#' Transition a stage.
#' 
#' Transition a model version's stage. This is a Databricks workspace version of
#' the [MLflow endpoint] that also accepts a comment associated with the
#' transition to be recorded.',
#' 
#' [MLflow endpoint]: https://www.mlflow.org/docs/latest/rest-api.html#transition-modelversion-stage
#' @param client Required. Instance of DatabricksClient()


#'
#'
#' @param archive_existing_versions Required. Specifies whether to archive all current model versions in the target stage.
#' @param comment User-provided comment on the action.
#' @param name Required. Name of the model.
#' @param stage Required. Target stage of the transition.
#' @param version Required. Version of the model.
#'
#' @rdname modelRegistryTransitionStage
#' @export
modelRegistryTransitionStage <- function(client, name, version, stage, archive_existing_versions,
  comment = NULL) {
  body <- list(archive_existing_versions = archive_existing_versions, comment = comment,
    name = name, stage = stage, version = version)
  client$do("POST", "/api/2.0/mlflow/databricks/model-versions/transition-stage",
    body = body)
}

#' Update a comment.
#' 
#' Post an edit to a comment on a model version.
#' @param client Required. Instance of DatabricksClient()


#'
#'
#' @param comment Required. User-provided comment on the action.
#' @param id Required. Unique identifier of an activity.
#'
#' @rdname modelRegistryUpdateComment
#' @export
modelRegistryUpdateComment <- function(client, id, comment) {
  body <- list(comment = comment, id = id)
  client$do("PATCH", "/api/2.0/mlflow/comments/update", body = body)
}

#' Update model.
#' 
#' Updates a registered model.
#' @param client Required. Instance of DatabricksClient()


#'
#'
#' @param description If provided, updates the description for this `registered_model`.
#' @param name Required. Registered model unique name identifier.
#'
#' @rdname modelRegistryUpdateModel
#' @export
modelRegistryUpdateModel <- function(client, name, description = NULL) {
  body <- list(description = description, name = name)
  client$do("PATCH", "/api/2.0/mlflow/registered-models/update", body = body)
}

#' Update model version.
#' 
#' Updates the model version.
#' @param client Required. Instance of DatabricksClient()


#'
#'
#' @param description If provided, updates the description for this `registered_model`.
#' @param name Required. Name of the registered model.
#' @param version Required. Model version number.
#'
#' @rdname modelRegistryUpdateModelVersion
#' @export
modelRegistryUpdateModelVersion <- function(client, name, version, description = NULL) {
  body <- list(description = description, name = name, version = version)
  client$do("PATCH", "/api/2.0/mlflow/model-versions/update", body = body)
}

#' Update registered model permissions.
#' 
#' Updates the permissions on a registered model. Registered models can inherit
#' permissions from their root object.
#' @param client Required. Instance of DatabricksClient()


#'
#'
#' @param access_control_list This field has no description yet.
#' @param registered_model_id Required. The registered model for which to get or manage permissions.
#'
#' @rdname modelRegistryUpdatePermissions
#' @export
modelRegistryUpdatePermissions <- function(client, registered_model_id, access_control_list = NULL) {
  body <- list(access_control_list = access_control_list)
  client$do("PATCH", paste("/api/2.0/permissions/registered-models/", registered_model_id,
    sep = ""), body = body)
}

#' Update a webhook.
#' 
#' **NOTE:** This endpoint is in Public Preview.
#' 
#' Updates a registry webhook.
#' @param client Required. Instance of DatabricksClient()


#'
#'
#' @param description User-specified description for the webhook.
#' @param events Events that can trigger a registry webhook: * `MODEL_VERSION_CREATED`: A new model version was created for the associated model.
#' @param http_url_spec This field has no description yet.
#' @param id Required. Webhook ID.
#' @param job_spec This field has no description yet.
#' @param status Enable or disable triggering the webhook, or put the webhook into test mode.
#'
#' @rdname modelRegistryUpdateWebhook
#' @export
modelRegistryUpdateWebhook <- function(client, id, description = NULL, events = NULL,
  http_url_spec = NULL, job_spec = NULL, status = NULL) {
  body <- list(description = description, events = events, http_url_spec = http_url_spec,
    id = id, job_spec = job_spec, status = status)
  client$do("PATCH", "/api/2.0/mlflow/registry-webhooks/update", body = body)
}

