# Code generated from OpenAPI specs by Databricks SDK Generator. DO NOT EDIT.

#' @importFrom stats runif
NULL

#' Approve transition request.
#' 
#' Approves a model version stage transition request.
#' @param client Required. Instance of DatabricksClient()
#'
#' @param archive_existing_versions Required. Specifies whether to archive all current model versions in the target stage.
#' @param comment User-provided comment on the action.
#' @param name Required. Name of the model.
#' @param stage Required. Target stage of the transition.
#' @param version Required. Version of the model.
#'
#' See the [API documentation](https://docs.databricks.com/api/workspace/modelregistry/approvetransitionrequest) for more 
#' information on the request and response field structure.
#'
#' @rdname approve_model_transition_request
#' @alias modelRegistryApproveTransitionRequest
#' @export
approve_model_transition_request <- function(client, name, version, stage, archive_existing_versions,
  comment = NULL) {
  body <- list(archive_existing_versions = archive_existing_versions, comment = comment,
    name = name, stage = stage, version = version)
  client$do("POST", "/api/2.0/mlflow/transition-requests/approve", body = body)
}

#' @rdname approve_model_transition_request
#' @export 
modelRegistryApproveTransitionRequest <- approve_model_transition_request
#' Post a comment.
#' 
#' Posts a comment on a model version. A comment can be submitted either by a
#' user or programmatically to display relevant information about the model. For
#' example, test results or deployment errors.
#' @param client Required. Instance of DatabricksClient()
#'
#' @param comment Required. User-provided comment on the action.
#' @param name Required. Name of the model.
#' @param version Required. Version of the model.
#'
#' See the [API documentation](https://docs.databricks.com/api/workspace/modelregistry/createcomment) for more 
#' information on the request and response field structure.
#'
#' @rdname create_model_comment
#' @alias modelRegistryCreateComment
#' @export
create_model_comment <- function(client, name, version, comment) {
  body <- list(comment = comment, name = name, version = version)
  client$do("POST", "/api/2.0/mlflow/comments/create", body = body)
}

#' @rdname create_model_comment
#' @export 
modelRegistryCreateComment <- create_model_comment
#' Create a model.
#' 
#' Creates a new registered model with the name specified in the request body.
#' 
#' Throws `RESOURCE_ALREADY_EXISTS` if a registered model with the given name
#' exists.
#' @param client Required. Instance of DatabricksClient()
#'
#' @param description Optional description for registered model.
#' @param name Required. Register models under this name.
#' @param tags Additional metadata for registered model.
#'
#' See the [API documentation](https://docs.databricks.com/api/workspace/modelregistry/createmodel) for more 
#' information on the request and response field structure.
#'
#' @rdname create_model
#' @alias modelRegistryCreateModel
#' @export
create_model <- function(client, name, description = NULL, tags = NULL) {
  body <- list(description = description, name = name, tags = tags)
  client$do("POST", "/api/2.0/mlflow/registered-models/create", body = body)
}

#' @rdname create_model
#' @export 
modelRegistryCreateModel <- create_model
#' Create a model version.
#' 
#' Creates a model version.
#' @param client Required. Instance of DatabricksClient()
#'
#' @param description Optional description for model version.
#' @param name Required. Register model under this name.
#' @param run_id MLflow run ID for correlation, if `source` was generated by an experiment run in MLflow tracking server.
#' @param run_link MLflow run link - this is the exact link of the run that generated this model version, potentially hosted at another instance of MLflow.
#' @param source Required. URI indicating the location of the model artifacts.
#' @param tags Additional metadata for model version.
#'
#' See the [API documentation](https://docs.databricks.com/api/workspace/modelregistry/createmodelversion) for more 
#' information on the request and response field structure.
#'
#' @rdname create_model_version
#' @alias modelRegistryCreateModelVersion
#' @export
create_model_version <- function(client, name, source, description = NULL, run_id = NULL,
  run_link = NULL, tags = NULL) {
  body <- list(description = description, name = name, run_id = run_id, run_link = run_link,
    source = source, tags = tags)
  client$do("POST", "/api/2.0/mlflow/model-versions/create", body = body)
}

#' @rdname create_model_version
#' @export 
modelRegistryCreateModelVersion <- create_model_version
#' Make a transition request.
#' 
#' Creates a model version stage transition request.
#' @param client Required. Instance of DatabricksClient()
#'
#' @param comment User-provided comment on the action.
#' @param name Required. Name of the model.
#' @param stage Required. Target stage of the transition.
#' @param version Required. Version of the model.
#'
#' See the [API documentation](https://docs.databricks.com/api/workspace/modelregistry/createtransitionrequest) for more 
#' information on the request and response field structure.
#'
#' @rdname create_model_transition_request
#' @alias modelRegistryCreateTransitionRequest
#' @export
create_model_transition_request <- function(client, name, version, stage, comment = NULL) {
  body <- list(comment = comment, name = name, stage = stage, version = version)
  client$do("POST", "/api/2.0/mlflow/transition-requests/create", body = body)
}

#' @rdname create_model_transition_request
#' @export 
modelRegistryCreateTransitionRequest <- create_model_transition_request
#' Create a webhook.
#' 
#' **NOTE**: This endpoint is in Public Preview.
#' 
#' Creates a registry webhook.
#' @param client Required. Instance of DatabricksClient()
#'
#' @param description User-specified description for the webhook.
#' @param events Required. Events that can trigger a registry webhook: * `MODEL_VERSION_CREATED`: A new model version was created for the associated model.
#' @param http_url_spec This field has no description yet.
#' @param job_spec This field has no description yet.
#' @param model_name Name of the model whose events would trigger this webhook.
#' @param status Enable or disable triggering the webhook, or put the webhook into test mode.
#'
#' See the [API documentation](https://docs.databricks.com/api/workspace/modelregistry/createwebhook) for more 
#' information on the request and response field structure.
#'
#' @rdname create_model_webhook
#' @alias modelRegistryCreateWebhook
#' @export
create_model_webhook <- function(client, events, description = NULL, http_url_spec = NULL,
  job_spec = NULL, model_name = NULL, status = NULL) {
  body <- list(description = description, events = events, http_url_spec = http_url_spec,
    job_spec = job_spec, model_name = model_name, status = status)
  client$do("POST", "/api/2.0/mlflow/registry-webhooks/create", body = body)
}

#' @rdname create_model_webhook
#' @export 
modelRegistryCreateWebhook <- create_model_webhook
#' Delete a comment.
#' 
#' Deletes a comment on a model version.
#' @param client Required. Instance of DatabricksClient()
#'
#' @param id Required. This field has no description yet.
#'
#' See the [API documentation](https://docs.databricks.com/api/workspace/modelregistry/deletecomment) for more 
#' information on the request and response field structure.
#'
#' @rdname delete_model_comment
#' @alias modelRegistryDeleteComment
#' @export
delete_model_comment <- function(client, id) {
  query <- list(id = id)
  client$do("DELETE", "/api/2.0/mlflow/comments/delete", query = query)
}

#' @rdname delete_model_comment
#' @export 
modelRegistryDeleteComment <- delete_model_comment
#' Delete a model.
#' 
#' Deletes a registered model.
#' @param client Required. Instance of DatabricksClient()
#'
#' @param name Required. Registered model unique name identifier.
#'
#' See the [API documentation](https://docs.databricks.com/api/workspace/modelregistry/deletemodel) for more 
#' information on the request and response field structure.
#'
#' @rdname delete_model
#' @alias modelRegistryDeleteModel
#' @export
delete_model <- function(client, name) {
  query <- list(name = name)
  client$do("DELETE", "/api/2.0/mlflow/registered-models/delete", query = query)
}

#' @rdname delete_model
#' @export 
modelRegistryDeleteModel <- delete_model
#' Delete a model tag.
#' 
#' Deletes the tag for a registered model.
#' @param client Required. Instance of DatabricksClient()
#'
#' @param key Required. Name of the tag.
#' @param name Required. Name of the registered model that the tag was logged under.
#'
#' See the [API documentation](https://docs.databricks.com/api/workspace/modelregistry/deletemodeltag) for more 
#' information on the request and response field structure.
#'
#' @rdname delete_model_tag
#' @alias modelRegistryDeleteModelTag
#' @export
delete_model_tag <- function(client, name, key) {
  query <- list(key = key, name = name)
  client$do("DELETE", "/api/2.0/mlflow/registered-models/delete-tag", query = query)
}

#' @rdname delete_model_tag
#' @export 
modelRegistryDeleteModelTag <- delete_model_tag
#' Delete a model version.
#' 
#' Deletes a model version.
#' @param client Required. Instance of DatabricksClient()
#'
#' @param name Required. Name of the registered model.
#' @param version Required. Model version number.
#'
#' See the [API documentation](https://docs.databricks.com/api/workspace/modelregistry/deletemodelversion) for more 
#' information on the request and response field structure.
#'
#' @rdname delete_model_version
#' @alias modelRegistryDeleteModelVersion
#' @export
delete_model_version <- function(client, name, version) {
  query <- list(name = name, version = version)
  client$do("DELETE", "/api/2.0/mlflow/model-versions/delete", query = query)
}

#' @rdname delete_model_version
#' @export 
modelRegistryDeleteModelVersion <- delete_model_version
#' Delete a model version tag.
#' 
#' Deletes a model version tag.
#' @param client Required. Instance of DatabricksClient()
#'
#' @param key Required. Name of the tag.
#' @param name Required. Name of the registered model that the tag was logged under.
#' @param version Required. Model version number that the tag was logged under.
#'
#' See the [API documentation](https://docs.databricks.com/api/workspace/modelregistry/deletemodelversiontag) for more 
#' information on the request and response field structure.
#'
#' @rdname delete_model_version_tag
#' @alias modelRegistryDeleteModelVersionTag
#' @export
delete_model_version_tag <- function(client, name, version, key) {
  query <- list(key = key, name = name, version = version)
  client$do("DELETE", "/api/2.0/mlflow/model-versions/delete-tag", query = query)
}

#' @rdname delete_model_version_tag
#' @export 
modelRegistryDeleteModelVersionTag <- delete_model_version_tag
#' Delete a transition request.
#' 
#' Cancels a model version stage transition request.
#' @param client Required. Instance of DatabricksClient()
#'
#' @param comment User-provided comment on the action.
#' @param creator Required. Username of the user who created this request.
#' @param name Required. Name of the model.
#' @param stage Required. Target stage of the transition request.
#' @param version Required. Version of the model.
#'
#' See the [API documentation](https://docs.databricks.com/api/workspace/modelregistry/deletetransitionrequest) for more 
#' information on the request and response field structure.
#'
#' @rdname delete_model_transition_request
#' @alias modelRegistryDeleteTransitionRequest
#' @export
delete_model_transition_request <- function(client, name, version, stage, creator,
  comment = NULL) {
  query <- list(comment = comment, creator = creator, name = name, stage = stage,
    version = version)
  client$do("DELETE", "/api/2.0/mlflow/transition-requests/delete", query = query)
}

#' @rdname delete_model_transition_request
#' @export 
modelRegistryDeleteTransitionRequest <- delete_model_transition_request
#' Delete a webhook.
#' 
#' **NOTE:** This endpoint is in Public Preview.
#' 
#' Deletes a registry webhook.
#' @param client Required. Instance of DatabricksClient()
#'
#' @param id Webhook ID required to delete a registry webhook.
#'
#' See the [API documentation](https://docs.databricks.com/api/workspace/modelregistry/deletewebhook) for more 
#' information on the request and response field structure.
#'
#' @rdname delete_model_webhook
#' @alias modelRegistryDeleteWebhook
#' @export
delete_model_webhook <- function(client, id = NULL) {
  query <- list(id = id)
  client$do("DELETE", "/api/2.0/mlflow/registry-webhooks/delete", query = query)
}

#' @rdname delete_model_webhook
#' @export 
modelRegistryDeleteWebhook <- delete_model_webhook
#' Get the latest version.
#' 
#' Gets the latest version of a registered model.
#' @param client Required. Instance of DatabricksClient()
#'
#' @param name Required. Registered model unique name identifier.
#' @param stages List of stages.
#'
#' @return `data.frame` with all of the response pages.
#'
#' See the [API documentation](https://docs.databricks.com/api/workspace/modelregistry/getlatestversions) for more 
#' information on the request and response field structure.
#'
#' @rdname get_model_latest_versions
#' @alias modelRegistryGetLatestVersions
#' @export
get_model_latest_versions <- function(client, name, stages = NULL) {
  body <- list(name = name, stages = stages)

  json <- client$do("POST", "/api/2.0/mlflow/registered-models/get-latest-versions",
    body = body)
  return(json$model_versions)

}

#' @rdname get_model_latest_versions
#' @export 
modelRegistryGetLatestVersions <- get_model_latest_versions
#' Get model.
#' 
#' Get the details of a model. This is a Databricks workspace version of the
#' MLflow endpoint that also returns the model's Databricks workspace ID and
#' the permission level of the requesting user on the model.
#' 
#' MLflow endpoint: https://www.mlflow.org/docs/latest/rest-api.html#get-registeredmodel
#' @param client Required. Instance of DatabricksClient()
#'
#' @param name Required. Registered model unique name identifier.
#'
#' See the [API documentation](https://docs.databricks.com/api/workspace/modelregistry/getmodel) for more 
#' information on the request and response field structure.
#'
#' @rdname get_model
#' @alias modelRegistryGetModel
#' @export
get_model <- function(client, name) {
  query <- list(name = name)
  client$do("GET", "/api/2.0/mlflow/databricks/registered-models/get", query = query)
}

#' @rdname get_model
#' @export 
modelRegistryGetModel <- get_model
#' Get a model version.
#' 
#' Get a model version.
#' @param client Required. Instance of DatabricksClient()
#'
#' @param name Required. Name of the registered model.
#' @param version Required. Model version number.
#'
#' See the [API documentation](https://docs.databricks.com/api/workspace/modelregistry/getmodelversion) for more 
#' information on the request and response field structure.
#'
#' @rdname get_model_version
#' @alias modelRegistryGetModelVersion
#' @export
get_model_version <- function(client, name, version) {
  query <- list(name = name, version = version)
  client$do("GET", "/api/2.0/mlflow/model-versions/get", query = query)
}

#' @rdname get_model_version
#' @export 
modelRegistryGetModelVersion <- get_model_version
#' Get a model version URI.
#' 
#' Gets a URI to download the model version.
#' @param client Required. Instance of DatabricksClient()
#'
#' @param name Required. Name of the registered model.
#' @param version Required. Model version number.
#'
#' See the [API documentation](https://docs.databricks.com/api/workspace/modelregistry/getmodelversiondownloaduri) for more 
#' information on the request and response field structure.
#'
#' @rdname get_model_version_download_uri
#' @alias modelRegistryGetModelVersionDownloadUri
#' @export
get_model_version_download_uri <- function(client, name, version) {
  query <- list(name = name, version = version)
  client$do("GET", "/api/2.0/mlflow/model-versions/get-download-uri", query = query)
}

#' @rdname get_model_version_download_uri
#' @export 
modelRegistryGetModelVersionDownloadUri <- get_model_version_download_uri
#' Get registered model permission levels.
#' 
#' Gets the permission levels that a user can have on an object.
#' @param client Required. Instance of DatabricksClient()
#'
#' @param registered_model_id Required. The registered model for which to get or manage permissions.
#'
#' See the [API documentation](https://docs.databricks.com/api/workspace/modelregistry/getpermissionlevels) for more 
#' information on the request and response field structure.
#'
#' @rdname get_model_permission_levels
#' @alias modelRegistryGetPermissionLevels
#' @export
get_model_permission_levels <- function(client, registered_model_id) {

  client$do("GET", paste("/api/2.0/permissions/registered-models/", registered_model_id,
    "/permissionLevels", , sep = ""))
}

#' @rdname get_model_permission_levels
#' @export 
modelRegistryGetPermissionLevels <- get_model_permission_levels
#' Get registered model permissions.
#' 
#' Gets the permissions of a registered model. Registered models can inherit
#' permissions from their root object.
#' @param client Required. Instance of DatabricksClient()
#'
#' @param registered_model_id Required. The registered model for which to get or manage permissions.
#'
#' See the [API documentation](https://docs.databricks.com/api/workspace/modelregistry/getpermissions) for more 
#' information on the request and response field structure.
#'
#' @rdname get_model_permissions
#' @alias modelRegistryGetPermissions
#' @export
get_model_permissions <- function(client, registered_model_id) {

  client$do("GET", paste("/api/2.0/permissions/registered-models/", registered_model_id,
    sep = ""))
}

#' @rdname get_model_permissions
#' @export 
modelRegistryGetPermissions <- get_model_permissions
#' List models.
#' 
#' Lists all available registered models, up to the limit specified in
#' __max_results__.
#' @param client Required. Instance of DatabricksClient()
#'
#' @param max_results Maximum number of registered models desired.
#' @param page_token Pagination token to go to the next page based on a previous query.
#'
#' @return `data.frame` with all of the response pages.
#'
#' See the [API documentation](https://docs.databricks.com/api/workspace/modelregistry/listmodels) for more 
#' information on the request and response field structure.
#'
#' @rdname list_model_models
#' @alias modelRegistryListModels
#' @export
list_model_models <- function(client, max_results = NULL, page_token = NULL) {
  query <- list(max_results = max_results, page_token = page_token)

  results <- data.frame()
  while (TRUE) {
    json <- client$do("GET", "/api/2.0/mlflow/registered-models/list", query = query)
    if (is.null(nrow(json$registered_models))) {
      break
    }
    # append this page of results to one results data.frame
    results <- dplyr::bind_rows(results, json$registered_models)
    if (is.null(json$next_page_token)) {
      break
    }
    query$page_token <- json$next_page_token
  }
  return(results)

}

#' @rdname list_model_models
#' @export 
modelRegistryListModels <- list_model_models
#' List transition requests.
#' 
#' Gets a list of all open stage transition requests for the model version.
#' @param client Required. Instance of DatabricksClient()
#'
#' @param name Required. Name of the model.
#' @param version Required. Version of the model.
#'
#' @return `data.frame` with all of the response pages.
#'
#' See the [API documentation](https://docs.databricks.com/api/workspace/modelregistry/listtransitionrequests) for more 
#' information on the request and response field structure.
#'
#' @rdname list_model_transition_requests
#' @alias modelRegistryListTransitionRequests
#' @export
list_model_transition_requests <- function(client, name, version) {
  query <- list(name = name, version = version)

  json <- client$do("GET", "/api/2.0/mlflow/transition-requests/list", query = query)
  return(json$requests)

}

#' @rdname list_model_transition_requests
#' @export 
modelRegistryListTransitionRequests <- list_model_transition_requests
#' List registry webhooks.
#' 
#' **NOTE:** This endpoint is in Public Preview.
#' 
#' Lists all registry webhooks.
#' @param client Required. Instance of DatabricksClient()
#'
#' @param events If `events` is specified, any webhook with one or more of the specified trigger events is included in the output.
#' @param model_name If not specified, all webhooks associated with the specified events are listed, regardless of their associated model.
#' @param page_token Token indicating the page of artifact results to fetch.
#'
#' @return `data.frame` with all of the response pages.
#'
#' See the [API documentation](https://docs.databricks.com/api/workspace/modelregistry/listwebhooks) for more 
#' information on the request and response field structure.
#'
#' @rdname list_model_webhooks
#' @alias modelRegistryListWebhooks
#' @export
list_model_webhooks <- function(client, events = NULL, model_name = NULL, page_token = NULL) {
  query <- list(events = events, model_name = model_name, page_token = page_token)

  results <- data.frame()
  while (TRUE) {
    json <- client$do("GET", "/api/2.0/mlflow/registry-webhooks/list", query = query)
    if (is.null(nrow(json$webhooks))) {
      break
    }
    # append this page of results to one results data.frame
    results <- dplyr::bind_rows(results, json$webhooks)
    if (is.null(json$next_page_token)) {
      break
    }
    query$page_token <- json$next_page_token
  }
  return(results)

}

#' @rdname list_model_webhooks
#' @export 
modelRegistryListWebhooks <- list_model_webhooks
#' Reject a transition request.
#' 
#' Rejects a model version stage transition request.
#' @param client Required. Instance of DatabricksClient()
#'
#' @param comment User-provided comment on the action.
#' @param name Required. Name of the model.
#' @param stage Required. Target stage of the transition.
#' @param version Required. Version of the model.
#'
#' See the [API documentation](https://docs.databricks.com/api/workspace/modelregistry/rejecttransitionrequest) for more 
#' information on the request and response field structure.
#'
#' @rdname reject_model_transition_request
#' @alias modelRegistryRejectTransitionRequest
#' @export
reject_model_transition_request <- function(client, name, version, stage, comment = NULL) {
  body <- list(comment = comment, name = name, stage = stage, version = version)
  client$do("POST", "/api/2.0/mlflow/transition-requests/reject", body = body)
}

#' @rdname reject_model_transition_request
#' @export 
modelRegistryRejectTransitionRequest <- reject_model_transition_request
#' Rename a model.
#' 
#' Renames a registered model.
#' @param client Required. Instance of DatabricksClient()
#'
#' @param name Required. Registered model unique name identifier.
#' @param new_name If provided, updates the name for this `registered_model`.
#'
#' See the [API documentation](https://docs.databricks.com/api/workspace/modelregistry/renamemodel) for more 
#' information on the request and response field structure.
#'
#' @rdname rename_model
#' @alias modelRegistryRenameModel
#' @export
rename_model <- function(client, name, new_name = NULL) {
  body <- list(name = name, new_name = new_name)
  client$do("POST", "/api/2.0/mlflow/registered-models/rename", body = body)
}

#' @rdname rename_model
#' @export 
modelRegistryRenameModel <- rename_model
#' Searches model versions.
#' 
#' Searches for specific model versions based on the supplied __filter__.
#' @param client Required. Instance of DatabricksClient()
#'
#' @param filter String filter condition, like 'name='my-model-name''.
#' @param max_results Maximum number of models desired.
#' @param order_by List of columns to be ordered by including model name, version, stage with an optional 'DESC' or 'ASC' annotation, where 'ASC' is the default.
#' @param page_token Pagination token to go to next page based on previous search query.
#'
#' @return `data.frame` with all of the response pages.
#'
#' See the [API documentation](https://docs.databricks.com/api/workspace/modelregistry/searchmodelversions) for more 
#' information on the request and response field structure.
#'
#' @rdname search_model_versions
#' @alias modelRegistrySearchModelVersions
#' @export
search_model_versions <- function(client, filter = NULL, max_results = NULL, order_by = NULL,
  page_token = NULL) {
  query <- list(filter = filter, max_results = max_results, order_by = order_by,
    page_token = page_token)

  results <- data.frame()
  while (TRUE) {
    json <- client$do("GET", "/api/2.0/mlflow/model-versions/search", query = query)
    if (is.null(nrow(json$model_versions))) {
      break
    }
    # append this page of results to one results data.frame
    results <- dplyr::bind_rows(results, json$model_versions)
    if (is.null(json$next_page_token)) {
      break
    }
    query$page_token <- json$next_page_token
  }
  return(results)

}

#' @rdname search_model_versions
#' @export 
modelRegistrySearchModelVersions <- search_model_versions
#' Search models.
#' 
#' Search for registered models based on the specified __filter__.
#' @param client Required. Instance of DatabricksClient()
#'
#' @param filter String filter condition, like 'name LIKE 'my-model-name''.
#' @param max_results Maximum number of models desired.
#' @param order_by List of columns for ordering search results, which can include model name and last updated timestamp with an optional 'DESC' or 'ASC' annotation, where 'ASC' is the default.
#' @param page_token Pagination token to go to the next page based on a previous search query.
#'
#' @return `data.frame` with all of the response pages.
#'
#' See the [API documentation](https://docs.databricks.com/api/workspace/modelregistry/searchmodels) for more 
#' information on the request and response field structure.
#'
#' @rdname search_model_models
#' @alias modelRegistrySearchModels
#' @export
search_model_models <- function(client, filter = NULL, max_results = NULL, order_by = NULL,
  page_token = NULL) {
  query <- list(filter = filter, max_results = max_results, order_by = order_by,
    page_token = page_token)

  results <- data.frame()
  while (TRUE) {
    json <- client$do("GET", "/api/2.0/mlflow/registered-models/search", query = query)
    if (is.null(nrow(json$registered_models))) {
      break
    }
    # append this page of results to one results data.frame
    results <- dplyr::bind_rows(results, json$registered_models)
    if (is.null(json$next_page_token)) {
      break
    }
    query$page_token <- json$next_page_token
  }
  return(results)

}

#' @rdname search_model_models
#' @export 
modelRegistrySearchModels <- search_model_models
#' Set a tag.
#' 
#' Sets a tag on a registered model.
#' @param client Required. Instance of DatabricksClient()
#'
#' @param key Required. Name of the tag.
#' @param name Required. Unique name of the model.
#' @param value Required. String value of the tag being logged.
#'
#' See the [API documentation](https://docs.databricks.com/api/workspace/modelregistry/setmodeltag) for more 
#' information on the request and response field structure.
#'
#' @rdname set_model_tag
#' @alias modelRegistrySetModelTag
#' @export
set_model_tag <- function(client, name, key, value) {
  body <- list(key = key, name = name, value = value)
  client$do("POST", "/api/2.0/mlflow/registered-models/set-tag", body = body)
}

#' @rdname set_model_tag
#' @export 
modelRegistrySetModelTag <- set_model_tag
#' Set a version tag.
#' 
#' Sets a model version tag.
#' @param client Required. Instance of DatabricksClient()
#'
#' @param key Required. Name of the tag.
#' @param name Required. Unique name of the model.
#' @param value Required. String value of the tag being logged.
#' @param version Required. Model version number.
#'
#' See the [API documentation](https://docs.databricks.com/api/workspace/modelregistry/setmodelversiontag) for more 
#' information on the request and response field structure.
#'
#' @rdname set_model_version_tag
#' @alias modelRegistrySetModelVersionTag
#' @export
set_model_version_tag <- function(client, name, version, key, value) {
  body <- list(key = key, name = name, value = value, version = version)
  client$do("POST", "/api/2.0/mlflow/model-versions/set-tag", body = body)
}

#' @rdname set_model_version_tag
#' @export 
modelRegistrySetModelVersionTag <- set_model_version_tag
#' Set registered model permissions.
#' 
#' Sets permissions on a registered model. Registered models can inherit
#' permissions from their root object.
#' @param client Required. Instance of DatabricksClient()
#'
#' @param access_control_list This field has no description yet.
#' @param registered_model_id Required. The registered model for which to get or manage permissions.
#'
#' See the [API documentation](https://docs.databricks.com/api/workspace/modelregistry/setpermissions) for more 
#' information on the request and response field structure.
#'
#' @rdname set_model_permissions
#' @alias modelRegistrySetPermissions
#' @export
set_model_permissions <- function(client, registered_model_id, access_control_list = NULL) {
  body <- list(access_control_list = access_control_list)
  client$do("PUT", paste("/api/2.0/permissions/registered-models/", registered_model_id,
    sep = ""), body = body)
}

#' @rdname set_model_permissions
#' @export 
modelRegistrySetPermissions <- set_model_permissions
#' Test a webhook.
#' 
#' **NOTE:** This endpoint is in Public Preview.
#' 
#' Tests a registry webhook.
#' @param client Required. Instance of DatabricksClient()
#'
#' @param event If `event` is specified, the test trigger uses the specified event.
#' @param id Required. Webhook ID.
#'
#' See the [API documentation](https://docs.databricks.com/api/workspace/modelregistry/testregistrywebhook) for more 
#' information on the request and response field structure.
#'
#' @rdname test_model_registry_webhook
#' @alias modelRegistryTestRegistryWebhook
#' @export
test_model_registry_webhook <- function(client, id, event = NULL) {
  body <- list(event = event, id = id)
  client$do("POST", "/api/2.0/mlflow/registry-webhooks/test", body = body)
}

#' @rdname test_model_registry_webhook
#' @export 
modelRegistryTestRegistryWebhook <- test_model_registry_webhook
#' Transition a stage.
#' 
#' Transition a model version's stage. This is a Databricks workspace version of
#' the MLflow endpoint that also accepts a comment associated with the
#' transition to be recorded.',
#' 
#' MLflow endpoint: https://www.mlflow.org/docs/latest/rest-api.html#transition-modelversion-stage
#' @param client Required. Instance of DatabricksClient()
#'
#' @param archive_existing_versions Required. Specifies whether to archive all current model versions in the target stage.
#' @param comment User-provided comment on the action.
#' @param name Required. Name of the model.
#' @param stage Required. Target stage of the transition.
#' @param version Required. Version of the model.
#'
#' See the [API documentation](https://docs.databricks.com/api/workspace/modelregistry/transitionstage) for more 
#' information on the request and response field structure.
#'
#' @rdname transition_model_stage
#' @alias modelRegistryTransitionStage
#' @export
transition_model_stage <- function(client, name, version, stage, archive_existing_versions,
  comment = NULL) {
  body <- list(archive_existing_versions = archive_existing_versions, comment = comment,
    name = name, stage = stage, version = version)
  client$do("POST", "/api/2.0/mlflow/databricks/model-versions/transition-stage",
    body = body)
}

#' @rdname transition_model_stage
#' @export 
modelRegistryTransitionStage <- transition_model_stage
#' Update a comment.
#' 
#' Post an edit to a comment on a model version.
#' @param client Required. Instance of DatabricksClient()
#'
#' @param comment Required. User-provided comment on the action.
#' @param id Required. Unique identifier of an activity.
#'
#' See the [API documentation](https://docs.databricks.com/api/workspace/modelregistry/updatecomment) for more 
#' information on the request and response field structure.
#'
#' @rdname update_model_comment
#' @alias modelRegistryUpdateComment
#' @export
update_model_comment <- function(client, id, comment) {
  body <- list(comment = comment, id = id)
  client$do("PATCH", "/api/2.0/mlflow/comments/update", body = body)
}

#' @rdname update_model_comment
#' @export 
modelRegistryUpdateComment <- update_model_comment
#' Update model.
#' 
#' Updates a registered model.
#' @param client Required. Instance of DatabricksClient()
#'
#' @param description If provided, updates the description for this `registered_model`.
#' @param name Required. Registered model unique name identifier.
#'
#' See the [API documentation](https://docs.databricks.com/api/workspace/modelregistry/updatemodel) for more 
#' information on the request and response field structure.
#'
#' @rdname update_model
#' @alias modelRegistryUpdateModel
#' @export
update_model <- function(client, name, description = NULL) {
  body <- list(description = description, name = name)
  client$do("PATCH", "/api/2.0/mlflow/registered-models/update", body = body)
}

#' @rdname update_model
#' @export 
modelRegistryUpdateModel <- update_model
#' Update model version.
#' 
#' Updates the model version.
#' @param client Required. Instance of DatabricksClient()
#'
#' @param description If provided, updates the description for this `registered_model`.
#' @param name Required. Name of the registered model.
#' @param version Required. Model version number.
#'
#' See the [API documentation](https://docs.databricks.com/api/workspace/modelregistry/updatemodelversion) for more 
#' information on the request and response field structure.
#'
#' @rdname update_model_version
#' @alias modelRegistryUpdateModelVersion
#' @export
update_model_version <- function(client, name, version, description = NULL) {
  body <- list(description = description, name = name, version = version)
  client$do("PATCH", "/api/2.0/mlflow/model-versions/update", body = body)
}

#' @rdname update_model_version
#' @export 
modelRegistryUpdateModelVersion <- update_model_version
#' Update registered model permissions.
#' 
#' Updates the permissions on a registered model. Registered models can inherit
#' permissions from their root object.
#' @param client Required. Instance of DatabricksClient()
#'
#' @param access_control_list This field has no description yet.
#' @param registered_model_id Required. The registered model for which to get or manage permissions.
#'
#' See the [API documentation](https://docs.databricks.com/api/workspace/modelregistry/updatepermissions) for more 
#' information on the request and response field structure.
#'
#' @rdname update_model_permissions
#' @alias modelRegistryUpdatePermissions
#' @export
update_model_permissions <- function(client, registered_model_id, access_control_list = NULL) {
  body <- list(access_control_list = access_control_list)
  client$do("PATCH", paste("/api/2.0/permissions/registered-models/", registered_model_id,
    sep = ""), body = body)
}

#' @rdname update_model_permissions
#' @export 
modelRegistryUpdatePermissions <- update_model_permissions
#' Update a webhook.
#' 
#' **NOTE:** This endpoint is in Public Preview.
#' 
#' Updates a registry webhook.
#' @param client Required. Instance of DatabricksClient()
#'
#' @param description User-specified description for the webhook.
#' @param events Events that can trigger a registry webhook: * `MODEL_VERSION_CREATED`: A new model version was created for the associated model.
#' @param http_url_spec This field has no description yet.
#' @param id Required. Webhook ID.
#' @param job_spec This field has no description yet.
#' @param status Enable or disable triggering the webhook, or put the webhook into test mode.
#'
#' See the [API documentation](https://docs.databricks.com/api/workspace/modelregistry/updatewebhook) for more 
#' information on the request and response field structure.
#'
#' @rdname update_model_webhook
#' @alias modelRegistryUpdateWebhook
#' @export
update_model_webhook <- function(client, id, description = NULL, events = NULL, http_url_spec = NULL,
  job_spec = NULL, status = NULL) {
  body <- list(description = description, events = events, http_url_spec = http_url_spec,
    id = id, job_spec = job_spec, status = status)
  client$do("PATCH", "/api/2.0/mlflow/registry-webhooks/update", body = body)
}

#' @rdname update_model_webhook
#' @export 
modelRegistryUpdateWebhook <- update_model_webhook




































