# Code generated from OpenAPI specs by Databricks SDK Generator. DO NOT EDIT.

#' Create a model version.
#' 
#' Creates a model version.
#'
#' @param description Optional description for model version.
#' @param name Register model under this name.
#' @param run_id MLflow run ID for correlation, if `source` was generated by an experiment run in MLflow tracking server.
#' @param run_link MLflow run link - this is the exact link of the run that generated this model version, potentially hosted at another instance of MLflow.
#' @param source URI indicating the location of the model artifacts.
#' @param tags Additional metadata for model version.
databricks_model_versions_create <- function(name, source, description = NULL, 
    run_id = NULL, 
    run_link = NULL, 
    tags = NULL, 
    ...) {
    body <- list(
        description = description, 
        name = name, 
        run_id = run_id, 
        run_link = run_link, 
        source = source, 
        tags = tags, ...)
    .api$do("POST", "/api/2.0/mlflow/model-versions/create", body = body)
}

#' Delete a model version.
#' 
#' Deletes a model version.
#'
#' @param name Name of the registered model.
#' @param version Model version number.
databricks_model_versions_delete <- function(name, version, ...) {
    query <- list(
        name = name, 
        version = version, ...)
    .api$do("DELETE", "/api/2.0/mlflow/model-versions/delete", query = query)
}

#' Delete a model version tag.
#' 
#' Deletes a model version tag.
#'
#' @param key Name of the tag.
#' @param name Name of the registered model that the tag was logged under.
#' @param version Model version number that the tag was logged under.
databricks_model_versions_delete_tag <- function(name, version, key, ...) {
    query <- list(
        key = key, 
        name = name, 
        version = version, ...)
    .api$do("DELETE", "/api/2.0/mlflow/model-versions/delete-tag", query = query)
}

#' Get a model version.
#' 
#' Get a model version.
#'
#' @param name Name of the registered model.
#' @param version Model version number.
databricks_model_versions_get <- function(name, version, ...) {
    query <- list(
        name = name, 
        version = version, ...)
    .api$do("GET", "/api/2.0/mlflow/model-versions/get", query = query)
}

#' Get a model version URI.
#' 
#' Gets a URI to download the model version.
#'
#' @param name Name of the registered model.
#' @param version Model version number.
databricks_model_versions_get_download_uri <- function(name, version, ...) {
    query <- list(
        name = name, 
        version = version, ...)
    .api$do("GET", "/api/2.0/mlflow/model-versions/get-download-uri", query = query)
}

#' Searches model versions.
#' 
#' Searches for specific model versions based on the supplied __filter__.
#'
#' @param filter String filter condition, like "name='my-model-name'".
#' @param max_results Maximum number of models desired.
#' @param order_by List of columns to be ordered by including model name, version, stage with an optional "DESC" or "ASC" annotation, where "ASC" is the default.
#' @param page_token Pagination token to go to next page based on previous search query.
databricks_model_versions_search <- function(filter = NULL, 
    max_results = NULL, 
    order_by = NULL, 
    page_token = NULL, 
    ...) {
    query <- list(
        filter = filter, 
        max_results = max_results, 
        order_by = order_by, 
        page_token = page_token, ...)
    .api$do("GET", "/api/2.0/mlflow/model-versions/search", query = query)
}

#' Set a version tag.
#' 
#' Sets a model version tag.
#'
#' @param key Name of the tag.
#' @param name Unique name of the model.
#' @param value String value of the tag being logged.
#' @param version Model version number.
databricks_model_versions_set_tag <- function(name, version, key, value, ...) {
    body <- list(
        key = key, 
        name = name, 
        value = value, 
        version = version, ...)
    .api$do("POST", "/api/2.0/mlflow/model-versions/set-tag", body = body)
}

#' Transition a stage.
#' 
#' Transition to the next model stage.
#'
#' @param archive_existing_versions When transitioning a model version to a particular stage, this flag dictates whether all existing model versions in that stage should be atomically moved to the "archived" stage.
#' @param name Name of the registered model.
#' @param stage Transition `model_version` to new stage.
#' @param version Model version number.
databricks_model_versions_transition_stage <- function(name, version, stage, archive_existing_versions, ...) {
    body <- list(
        archive_existing_versions = archive_existing_versions, 
        name = name, 
        stage = stage, 
        version = version, ...)
    .api$do("POST", "/api/2.0/mlflow/model-versions/transition-stage", body = body)
}

#' Update model version.
#' 
#' Updates the model version.
#'
#' @param description If provided, updates the description for this `registered_model`.
#' @param name Name of the registered model.
#' @param version Model version number.
databricks_model_versions_update <- function(name, version, description = NULL, 
    ...) {
    body <- list(
        description = description, 
        name = name, 
        version = version, ...)
    .api$do("PATCH", "/api/2.0/mlflow/model-versions/update", body = body)
}

