name: acceptance

on:
  pull_request:
    types: [opened, synchronize]

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  integration:
    if: github.event_name == 'pull_request'
    environment: admin
    runs-on: larger
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2.5.0

      - name: Unshallow
        run: git fetch --prune --unshallow

      - uses: actions/checkout@v3

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: release
          use-public-rspm: true
    
      - uses: azure/login@v1
        with:
          client-id: ${{ secrets.ARM_CLIENT_ID }}
          tenant-id: ${{ secrets.ARM_TENANT_ID }}
          allow-no-subscriptions: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: devtools
          env:
          R_COMPILE_AND_INSTALL_PACKAGES: never
        
      - name: Run tests
        run: Rscript -e "devtools::test()"
        env:
          CLOUD_ENV: "${{ vars.CLOUD_ENV }}"
          DATABRICKS_HOST: "${{ secrets.DATABRICKS_HOST }}"
      